name:                latypinf
version:             0.1.1
github:              raehik/ukc-co663-latypinf
license:             MIT
author:              Ben Orchard / bo207 / @raehik
copyright:           "2020 Ben Orchard (@raehik) <thefirstmuffinman@gmail.com>"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/raehik/ukc-co663-latypinf#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2
- mtl >= 2.2
- transformers >= 0.5
- containers >= 0.6

library:
  source-dirs: src

executables:
  latypinf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - latypinf
